---
- name: Automate sosreport upload to Red Hat case
  hosts: '{{ target_host }}'
  gather_facts: true
  vars_prompt:
    - name: "case_number"
      prompt: "Enter the Red Hat case number"
      private: no
    - name: "offline_token"
      prompt: "Enter your Red Hat offline token"
      private: yes
  tasks:
    - name: Get a new access token from Red Hat API
      ansible.builtin.uri:
        url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
        method: POST
        body_format: form-urlencoded
        body:
          grant_type: "refresh_token"
          client_id: "rhsm-api"
          refresh_token: "{{ offline_token }}"
      register: token_response

    - name: Set access token variable
      ansible.builtin.set_fact:
        access_token: "{{ token_response.json.access_token }}"

    - name: Run sos report command
      ansible.builtin.command: 'sos report --batch --case-id {{ case_number }}'
      args:
        chdir: /var/tmp
      register: sosreport_output
      become: yes

    - name: Find the generated sosreport archive
      ansible.builtin.find:
        paths: /var/tmp
        patterns: "sosreport-{{ ansible_hostname }}-{{ case_number }}-*.tar.xz"
        age: "1m"
      register: sosreport_file

    - name: Upload sosreport file to Red Hat case via curl
      when: sosreport_file.files | length > 0
      ansible.builtin.command: >
        curl -v -k -X POST -H "Authorization: Bearer {{ access_token }}"
        -H "Content-Type: application/x-xz"
